import hashlib
from pathlib import Path
from log import *

# The hash_utils module ensures that the program works only with authentic
# and unmodified files that were originally generated by it.
# If any modification occurs, the program detects the integrity violation,
# rejects the invalid files, and notifies the user or regenerates them.

def generate_sha256(file_path):
    """
    Generates the SHA-256 hash value for the given file.
    The file is read in binary chunks to efficiently process files of any size.
    Returns the final hash value as a hexadecimal string.
    """
    sha256 = hashlib.sha256()

    with open(file_path, "rb") as f:

        while chunk := f.read(4096):
            sha256.update(chunk)

    return sha256.hexdigest()


def save_hash(file_path): 
    # This function generates the SHA-256 hash value for the given file.
    # It stores the hash value in a corresponding .sha256 file.

    hash_value = generate_sha256(file_path)
    hash_file = Path(str(file_path) + ".sha256")

    with open(hash_file, "w") as f:
        f.write(hash_value)

    return hash_file



def verify_hash(file_path):
    
    # This function verifies the integrity of the given file by comparing
    # its current SHA-256 hash with the previously stored hash value.
    # Any modification to the original file will result in a hash mismatch.

    hash_file = Path(str(file_path) + ".sha256")

    if not hash_file.exists():
        return False
    
    stored_hash = hash_file.read_text() 
    current_hash = generate_sha256(file_path)       # Returns False if a hash mismatch occurs, meaning the file has been modified.
                                                    # Returns True if the current hash matches the stored hash and no changes have been made.
    return stored_hash == current_hash 


def hashUse(path, mode):  
    # This function can be used in the main program.
    # It receives the mode parameter to determine which action should be performed.
    
    if (mode == 0): #create new file
        save_hash(path)
        log("Successfully created hash file.")
    elif (mode == 1): #verify hash
        if verify_hash(path):
            log("Hash check succesfully completed.")
            return True
        else:
            log ("Data is corrupted or sha256 does not exist.")
            print("Data is corrupted or files missing.")
            return False
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    



